-- INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
-- VALUES('U1','B1')
-- ;
INSERT INTO auth_names (AUTH_NAME, UNIQUE_ID)
VALUES ('GUEST','B1')
;


INSERT INTO users (UNIQUE_ID, NAME, EAMIL, JOB)
VALUES ('U1', 'Paul', 'paul01@gmail.com',  'IT Billing')
;
INSERT INTO users (UNIQUE_ID, NAME, EAMIL, JOB)
VALUES ('U2', 'Allen'	 ,'texas@imfblog.org'	,'Engineering')
;
INSERT INTO users (UNIQUE_ID, NAME, EAMIL, JOB)
VALUES ('U3',	'Teddy',	 'norway@iotm.com',	'IT Billing')
;
INSERT INTO users (UNIQUE_ID, NAME, EAMIL, JOB)
VALUES ('U4'	,'Paul',	'paul_p@naver.com'	,'Developer')
;
INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U1',	'B1')
;
INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U2',	'B2')
;
INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U3',	'B3')
;
INSERT INTO auths (UNIQUE_ID_USERS, UNIQUE_ID_AUTH_NAMES)
VALUES ('U4',	'B4')
;


-- DELETE FROM users
-- WHERE UNIQUE_ID = 'U1'

SELECT *
FROM users;